handleGHRelease: true
releaseLabels:
  - "release"
  - "automated pr"
branches:
  main:
    releaseType: simple
    prerelease: false
    bumpMinorPreMajor: true
    initialVersion: "1.2.0"
  dev:
    releaseType: simple
    prerelease: true
    prereleaseSuffix: rc
    preTitlePattern: "chore: release ${version}"
    bumpMinorPreMajor: true
    initialVersion: "1.2.0"
    handleGHRelease: true
    draft: true
